import type { ProjectConfig } from '@/types';

// 워크스페이스 프로젝트 정의
export const GITHUB_OWNER = 'clusteruni-debug';

export const PROJECTS: ProjectConfig[] = [
  {
    name: 'Navigator',
    folder: 'To-do-list-for-adhd',
    repo: 'To-do-list-for-adhd',
    description: 'ADHD 맞춤 할 일 관리 + 라이프 리듬',
    techStack: ['HTML', 'Vanilla JS', 'Firebase'],
    category: 'running',
    platform: 'windows',
    runCmd: 'npx serve -p 5000',
    port: 5000,
    connections: ['telegram-event-bot', 'web3-budget-app', 'article-editor'],
    phase: '운영 안정화',
    completionPct: 85,
    nextTasks: ['습관 트래커 확장', '스트릭 시각화'],
    priority: 'medium',
  },
  {
    name: 'Kimchi Premium',
    folder: 'Kimpbotforme',
    repo: 'Kimpbotforme',
    description: '크립토 김치 프리미엄 모니터링',
    techStack: ['React', 'Vite', 'WebSocket'],
    category: 'running',
    platform: 'windows',
    runCmd: 'cd react-app && npm run dev',
    port: 5173,
    phase: 'v5.5 운영중',
    completionPct: 90,
    nextTasks: ['알림 임계값 커스텀'],
    priority: 'maintenance',
  },
  {
    name: 'Web3 가계부',
    folder: 'web3-budget-app',
    repo: 'web3-budget-app',
    description: '자산 관리 + 가계부',
    techStack: ['Vite', 'Vanilla JS', 'Supabase'],
    category: 'running',
    platform: 'windows',
    runCmd: 'npx vite --port 5173',
    port: 5173,
    connections: ['To-do-list-for-adhd'],
    phase: '운영 안정화',
    completionPct: 80,
    nextTasks: ['부부 공유 기능', '세금 계산기'],
    priority: 'medium',
  },
  {
    name: 'Telegram Bot',
    folder: 'telegram-event-bot',
    repo: 'telegram-event-bot',
    description: '텔레그램 이벤트 알림 봇',
    techStack: ['Python', 'Flask', 'Supabase'],
    category: 'running',
    platform: 'windows',
    runCmd: 'python web.py',
    port: 5001,
    connections: ['To-do-list-for-adhd'],
    phase: '운영 안정화',
    completionPct: 90,
    nextTasks: ['경로 안정화 완료 검증'],
    priority: 'maintenance',
  },
  {
    name: 'Baby Care',
    folder: 'baby-care',
    repo: 'baby-care',
    description: '아기 케어 기록 앱',
    techStack: ['Next.js', 'TypeScript', 'Firebase'],
    category: 'dev',
    platform: 'windows',
    runCmd: 'npm run dev',
    port: 3000,
    phase: 'MVP 완료',
    completionPct: 75,
    nextTasks: ['통계 대시보드', '가족 공유'],
    priority: 'medium',
  },
  {
    name: 'Article Editor',
    folder: 'article-editor',
    repo: 'article-editor',
    description: 'X 아티클 작성 에디터',
    techStack: ['Next.js', 'Supabase', 'TipTap'],
    category: 'dev',
    platform: 'windows',
    runCmd: 'npm run dev',
    port: 3000,
    connections: ['To-do-list-for-adhd'],
    phase: 'MVP 완료',
    completionPct: 70,
    nextTasks: ['AI 글쓰기 보조', '퍼블리싱 연동'],
    priority: 'low',
  },
  {
    name: 'Text RPG',
    folder: 'ramgtd-text-rpg',
    repo: 'ramgtd-text-rpg',
    description: '텍스트 기반 RPG 게임',
    techStack: ['Vite', 'Vanilla JS'],
    category: 'dev',
    platform: 'windows',
    runCmd: 'npm run dev',
    port: 5173,
    phase: '콘텐츠 확장 완료',
    completionPct: 65,
    nextTasks: ['세이브/로드', '사운드 효과'],
    priority: 'low',
  },
  {
    name: 'Portfolio',
    folder: 'portfolio',
    repo: 'portfolio',
    description: '포트폴리오 사이트',
    techStack: ['Vite', 'React', 'TypeScript'],
    category: 'dev',
    platform: 'windows',
    runCmd: 'npm run dev',
    port: 5173,
    phase: '리디자인 완료',
    completionPct: 85,
    nextTasks: ['GH Pages 배포', '프로젝트 상세 페이지'],
    priority: 'medium',
  },
  {
    name: 'Saitama Training',
    folder: 'saitama-training',
    repo: 'Saitama-training',
    description: '사이타마 트레이닝 추적',
    techStack: ['React', 'TypeScript', 'Firebase', 'Zustand'],
    category: 'dev',
    platform: 'windows',
    runCmd: 'npm run dev',
    port: 5173,
    phase: 'MVP 완료',
    completionPct: 60,
    nextTasks: ['운동 통계', '친구 경쟁'],
    priority: 'low',
  },
  {
    name: 'Make Money',
    folder: 'make-money-project',
    repo: 'make-money-project',
    description: 'Polymarket AI 자동매매 봇 + 운영 대시보드',
    techStack: ['Node.js', 'Express', 'React', 'SQLite', 'Claude AI'],
    category: 'running',
    platform: 'windows',
    runCmd: 'cd server && node index.js',
    port: 3001,
    phase: '엔진 튜닝',
    completionPct: 70,
    nextTasks: ['시그널 가뭄 해소', 'dry-run 모드', '엔진 성과 분석'],
    priority: 'high',
  },
  {
    name: 'OpenClaw',
    folder: 'claude-code-bot',
    repo: 'openclaw-bot',
    description: '텔레그램→Claude Code 자율 코딩봇',
    techStack: ['Python', 'python-telegram-bot', 'Claude Code CLI'],
    category: 'tool',
    platform: 'wsl',
    runCmd: 'cd /mnt/c/vibe/projects/claude-code-bot && python bot.py',
    phase: '인프라 완성 / UX 개선 중',
    completionPct: 50,
    nextTasks: ['/dashboard 명령', '에러 해석 보고', '일일 보고서'],
    priority: 'high',
  },
  {
    name: 'Claude Skills',
    folder: 'Claude-skills',
    repo: 'Claude-skills',
    description: 'Claude Code 커스텀 스킬 모음',
    techStack: ['Shell', 'Markdown'],
    category: 'tool',
    platform: 'both',
    runCmd: './setup.sh',
    phase: '운영중',
    completionPct: 90,
    nextTasks: ['스킬 카탈로그 정리'],
    priority: 'maintenance',
  },
  {
    name: 'Mission Control',
    folder: 'mission-control',
    repo: 'mission-control',
    description: '워크스페이스 프로젝트 관제 대시보드',
    techStack: ['Next.js', 'TypeScript', 'Supabase'],
    category: 'tool',
    deployUrl: 'https://mission-control-psi-smoky.vercel.app',
    platform: 'windows',
    runCmd: 'npm run dev',
    port: 3000,
    phase: '로드맵 뷰 추가 중',
    completionPct: 75,
    nextTasks: ['phase/진행바 표시', '우선순위 정렬'],
    priority: 'high',
  },
];

export const CATEGORY_LABELS: Record<ProjectConfig['category'], string> = {
  running: '운영중',
  dev: '개발중',
  legacy: '레거시',
  tool: '도구',
};

export const CATEGORY_COLORS: Record<ProjectConfig['category'], string> = {
  running: 'bg-green-500',
  dev: 'bg-blue-500',
  legacy: 'bg-gray-500',
  tool: 'bg-purple-500',
};

export const PRIORITY_LABELS: Record<import('@/types').ProjectPriority, string> = {
  high: '높음',
  medium: '보통',
  low: '낮음',
  maintenance: '유지보수',
};

export const PRIORITY_COLORS: Record<import('@/types').ProjectPriority, string> = {
  high: 'bg-red-100 text-red-700 dark:bg-red-900 dark:text-red-300',
  medium: 'bg-yellow-100 text-yellow-700 dark:bg-yellow-900 dark:text-yellow-300',
  low: 'bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400',
  maintenance: 'bg-blue-100 text-blue-600 dark:bg-blue-900 dark:text-blue-300',
};
