import type { ProjectConfig } from '@/types';

// 워크스페이스 프로젝트 정의
export const GITHUB_OWNER = 'clusteruni-debug';

export const PROJECTS: ProjectConfig[] = [
  {
    name: 'Navigator',
    folder: 'To-do-list-for-adhd',
    repo: 'To-do-list-for-adhd',
    description: 'ADHD 맞춤 할 일 관리 + 라이프 리듬 + 캘린더',
    techStack: ['HTML', 'Vanilla JS', 'Firebase'],
    category: 'running',
    deployUrl: 'https://clusteruni-debug.github.io/To-do-list-for-adhd/navigator-v5.html',
    platform: 'windows',
    runCmd: 'npx serve -p 5000',
    port: 5000,
    connections: ['telegram-event-bot', '자산관리', 'x-article-editor'],
    phase: '리듬/히스토리 UX 개선 완료',
    completionPct: 94,
    nextTasks: ['PC 최적화', '추가 UX 조정'],
    priority: 'medium',
  },
  {
    name: 'Kimchi Premium',
    folder: 'kimchi-premium',
    repo: 'Kimpbotforme',
    description: '크립토 김치 프리미엄 모니터링',
    techStack: ['React', 'Vite', 'WebSocket'],
    category: 'running',
    platform: 'windows',
    runCmd: 'cd react-app && npx vite --port 5100',
    port: 5100,
    phase: '모듈 분리 + v5.5 운영',
    completionPct: 92,
    nextTasks: ['알림 임계값 커스텀'],
    priority: 'maintenance',
  },
  {
    name: '자산관리',
    folder: '자산관리',
    repo: 'web3-budget-app',
    description: '자산 관리 + 가계부',
    techStack: ['Vite', 'Vanilla JS', 'Supabase'],
    category: 'running',
    deployUrl: 'https://web3-budget-app.vercel.app/',
    platform: 'windows',
    runCmd: 'npx vite --port 5140',
    port: 5140,
    connections: ['To-do-list-for-adhd'],
    phase: '모듈 분리 + 운영 안정화',
    completionPct: 88,
    nextTasks: ['세금 계산기'],
    priority: 'medium',
  },
  {
    name: 'Telegram Bot',
    folder: 'telegram-event-bot',
    repo: 'telegram-event-bot',
    description: '텔레그램 이벤트 알림 봇 (Bot→WSL, Web→Vercel)',
    techStack: ['Python', 'Flask', 'Supabase'],
    category: 'running',
    deployUrl: 'https://telegram-event-bot-ashy.vercel.app',
    platform: 'wsl',
    runCmd: 'systemctl --user status telegram-event-bot',
    connections: ['To-do-list-for-adhd'],
    phase: '장애 복구 + 방어 코드 개선',
    completionPct: 94,
    nextTasks: ['WSL↔Win 파일 동기화', 'insight 분류 모니터링'],
    priority: 'maintenance',
  },
  {
    name: 'Baby Care',
    folder: 'baby-care',
    repo: 'baby-care',
    description: '아기 케어 기록 앱',
    techStack: ['Next.js', 'TypeScript', 'Firebase'],
    category: 'dev',
    deployUrl: 'https://baby-care-gilt.vercel.app/',
    platform: 'windows',
    runCmd: 'npx next dev --turbopack -p 3020',
    port: 3020,
    phase: '모듈 분리 + 기능 확장',
    completionPct: 87,
    nextTasks: ['데이터 내보내기', '성장 차트 오버레이'],
    priority: 'medium',
  },
  {
    name: 'Article Editor',
    folder: 'x-article-editor',
    repo: 'article-editor',
    description: 'X 아티클 작성 에디터',
    techStack: ['Next.js', 'Supabase', 'TipTap'],
    category: 'dev',
    deployUrl: 'https://article-editor-ruddy.vercel.app/',
    platform: 'windows',
    runCmd: 'npx next dev -p 3010',
    port: 3010,
    connections: ['To-do-list-for-adhd'],
    phase: '모듈 분리 + AI 통합',
    completionPct: 82,
    nextTasks: ['퍼블리싱 연동', 'AI 프롬프트 개선'],
    priority: 'low',
  },
  {
    name: 'Text RPG',
    folder: 'text-rpg',
    repo: 'ramgtd-text-rpg',
    description: '텍스트 기반 RPG 게임',
    techStack: ['Vite', 'Vanilla JS'],
    category: 'dev',
    platform: 'windows',
    runCmd: 'npx vite --port 5120',
    port: 5120,
    phase: '모듈 분리 + 콘텐츠 확장',
    completionPct: 77,
    nextTasks: ['사운드 효과', '동료 시스템', '엔그램 밸런싱'],
    priority: 'low',
  },
  {
    name: 'Portfolio',
    folder: 'portfolio',
    repo: 'portfolio',
    description: '포트폴리오 사이트',
    techStack: ['Vite', 'React', 'TypeScript'],
    category: 'dev',
    deployUrl: 'https://clusteruni-debug.github.io/portfolio/',
    platform: 'windows',
    runCmd: 'npx vite --port 5110',
    port: 5110,
    phase: 'GH Pages 배포 완료',
    completionPct: 90,
    nextTasks: ['프로젝트 상세 페이지', '스크린샷 교체'],
    priority: 'medium',
  },
  {
    name: 'Saitama Training',
    folder: 'Saitama-training',
    repo: 'Saitama-training',
    description: '사이타마 트레이닝 추적',
    techStack: ['React', 'TypeScript', 'Firebase', 'Zustand'],
    category: 'dev',
    platform: 'windows',
    runCmd: 'npx vite --port 5130',
    port: 5130,
    phase: '모듈 분리 + MVP 완료',
    completionPct: 62,
    nextTasks: ['운동 통계', '친구 경쟁'],
    priority: 'low',
  },
  {
    name: 'Make Money',
    folder: 'make-money-project',
    repo: 'make-money-project',
    description: '크립토 AI 자동매매 봇 + 운영 대시보드',
    techStack: ['Node.js', 'Express', 'React', 'SQLite', 'Claude AI'],
    category: 'running',
    platform: 'windows',
    runCmd: 'cd server && node index.js',
    port: 3001,
    phase: 'recovery 전략 실전 운영',
    completionPct: 75,
    nextTasks: ['recovery 20건 성과 평가', '$50 도달 시 balanced 전환', '코드 분리 런타임 검증'],
    priority: 'high',
  },
  {
    name: 'Watch Bot',
    folder: 'claude-code-bot',
    repo: 'openclaw-bot',
    description: '텔레그램→Claude Code 워치봇 (은퇴 — OpenClaw로 대체)',
    techStack: ['Python', 'python-telegram-bot', 'Claude Code CLI'],
    category: 'legacy',
    platform: 'wsl',
    runCmd: 'cd /mnt/c/vibe/projects/claude-code-bot && python bot.py',
    phase: '은퇴',
    completionPct: 100,
    nextTasks: [],
    priority: 'maintenance',
  },
  {
    name: 'Claude Skills',
    folder: 'Claude-skills',
    repo: 'Claude-skills',
    description: 'Claude Code 커스텀 스킬 모음',
    techStack: ['Shell', 'Markdown'],
    category: 'tool',
    platform: 'both',
    runCmd: './setup.sh',
    phase: '운영중',
    completionPct: 90,
    nextTasks: ['스킬 카탈로그 정리'],
    priority: 'maintenance',
  },
  {
    name: 'TRADINGLAB',
    folder: 'coin-test-project',
    repo: 'coin-test-project',
    description: '크립토 트레이딩 실험실',
    techStack: ['Python', 'pandas', 'ccxt', 'Jinja2'],
    category: 'dev',
    platform: 'windows',
    runCmd: 'python -m tradinglab dashboard',
    port: 8787,
    phase: '튜닝 제약 검증 완료',
    completionPct: 68,
    nextTasks: ['feasible 판정 호출부 연결', 'walk-forward 자동화'],
    priority: 'medium',
  },
  {
    name: 'AI Hub',
    folder: 'ai-hub',
    repo: 'ai-hub',
    description: 'Multi-AI LLM 서비스 허브 + 대화 관리 대시보드',
    techStack: ['Electron', 'Vanilla JS', 'Supabase'],
    category: 'tool',
    platform: 'windows',
    runCmd: 'npx electron-vite dev',
    port: 5150,
    phase: '다중 파일 가져오기 + 중복 감지 강화',
    completionPct: 35,
    nextTasks: ['다중 파일 E2E 테스트', '휴면 시스템'],
    priority: 'medium',
  },
  {
    name: 'AI Hub Extension',
    folder: 'ai-hub-extension',
    repo: 'ai-hub-extension',
    description: 'AI Hub Chrome 확장 — 본문 저장 + 중복 감지',
    techStack: ['Chrome Extension MV3', 'Supabase'],
    category: 'tool',
    platform: 'windows',
    phase: '본문 저장 + 중복 감지 완료',
    completionPct: 40,
    nextTasks: ['Chrome Web Store 심사', 'UI 고도화'],
    priority: 'medium',
  },
  {
    name: 'Mission Control',
    folder: 'mission-control',
    repo: 'mission-control',
    description: '워크스페이스 프로젝트 관제 대시보드',
    techStack: ['Next.js', 'TypeScript', 'Supabase'],
    category: 'tool',
    deployUrl: 'https://mission-control-psi-smoky.vercel.app',
    platform: 'windows',
    runCmd: 'npm run dev',
    port: 3000,
    phase: '로드맵 뷰 완료',
    completionPct: 85,
    nextTasks: ['프로젝트 상세 뷰', '타임라인 시각화'],
    priority: 'medium',
  },
];

export const CATEGORY_LABELS: Record<ProjectConfig['category'], string> = {
  running: '운영중',
  dev: '개발중',
  legacy: '레거시',
  tool: '도구',
};

export const CATEGORY_COLORS: Record<ProjectConfig['category'], string> = {
  running: 'bg-green-500',
  dev: 'bg-blue-500',
  legacy: 'bg-gray-500',
  tool: 'bg-purple-500',
};

export const PRIORITY_LABELS: Record<import('@/types').ProjectPriority, string> = {
  high: '높음',
  medium: '보통',
  low: '낮음',
  maintenance: '유지보수',
};

export const PRIORITY_COLORS: Record<import('@/types').ProjectPriority, string> = {
  high: 'bg-red-100 text-red-700 dark:bg-red-900 dark:text-red-300',
  medium: 'bg-yellow-100 text-yellow-700 dark:bg-yellow-900 dark:text-yellow-300',
  low: 'bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400',
  maintenance: 'bg-blue-100 text-blue-600 dark:bg-blue-900 dark:text-blue-300',
};
